### ISSUE TITLE
Add methods related to random numbers

### ISSUE THREAD

**Issue by simoneddeland** [simoneddeland/proc-sharp#3]
See the reference under the heading "Random" at https://processing.org/reference/

**Comment by fistaco** [comment]
I'll take this issue. Will do my best to implement the methods according to the original library's implementations!

**Comment by simoneddeland** [comment]
> I'll take this issue. Will do my best to implement the methods according to the original library's implementations!

Awesome!

**Comment by simoneddeland** [comment]
@fistaco I updated the CONTRIBUTING.md to show the easiest way to get ProcSharp up and running when updating the source code, check it out [here](https://github.com/simoneddeland/proc-sharp/blob/master/CONTRIBUTING.md)

**Comment by fistaco** [comment]
Thanks! I'll follow the newly added instructions for testing.

**Comment by simoneddeland** [comment]
Fixed in https://github.com/simoneddeland/proc-sharp/pull/6
